import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Eyebrow } from '../components/Section'
const words=['Docs','Teams','AI']
const caps=[['Documents','Real-time documents for teams to write together','extract-1.png'],['Writers','Polished word processing for every shared draft','extract-2.png'],['Spreadsheets','Flexible sheets for shared data and decisions','extract-3.png'],['Presentations','Collaborative slides that keep the story moving','extract-4.png'],['App sheets','Apps and tables for projects that stay on track','extract-5.png'],['Forms','Forms that turn responses into usable context','extract-6.png']]
const scenes=[['Knowledge management','Build a team knowledge hub.','extract-2.png'],['Project management','Plan a project launch.','extract-3.png'],['Meeting notes','Capture meeting decisions.','extract-6.png'],['Policy & SOPs','Keep operating knowledge current.','extract-1.png'],['Marketing planning','Prepare an executive review.','extract-4.png'],['HR onboarding','Run employee onboarding.','extract-7.png']]
export default function Home(){const [word,setWord]=useState(0); const [scene,setScene]=useState(0); useEffect(()=>{const id=setInterval(()=>setWord(v=>(v+1)%words.length),2200);return()=>clearInterval(id)},[]); return <div className="page home-page">
  <section className="hero-home"><div className="hero-copy"><Eyebrow>The modern workspace for modern teams</Eyebrow><h1>ShimoDocs helps you work with <span className="rotating-word" key={word}>{words[word]}</span><span className="gradient">.</span></h1><p>Create, organize and move work forward in one connected workspace — from the first note to the final decision.</p><div className="hero-actions"><Link className="button" to="/ai-workspace">Explore AI Workspace</Link><a className="text-link" href="#scenes">See what teams do ↗</a></div></div><div className="hero-product"><img src="/assets/extract-0.png" alt="ShimoDocs collaborative product launch plan"/><div className="ai-cursor"><span>✦</span> AI</div><div className="ai-comment"><div><b>Shimo AI</b><small>Just now</small><i>✓</i></div><p>Grouped the launch tasks into a clearer sequence.</p><em>AI suggestion</em></div></div></section>
  <section className="section"><Eyebrow>Everything your work needs</Eyebrow><h2>Six capabilities.<br/><span className="gradient">One connected system.</span></h2><p className="section-lead">Docs, data, stories and intake live together, so teams can move from context to action without changing tools.</p><div className="cap-grid">{caps.map(([title,desc,img],i)=><article className="cap-card" key={title}><img src={`/assets/${img}`} alt={`${title} interface`}/><div className="cap-overlay"><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p></div></article>)}</div></section>
  <section className="section scenes-section" id="scenes"><div className="section-heading"><div><Eyebrow>Built around real work</Eyebrow><h2>Pick a scene.<br/><span className="gradient">Watch it move.</span></h2></div><p className="section-lead">Start with the work in front of you and keep every decision connected.</p></div><div className="scene-pills">{scenes.map(([label],i)=><button key={label} onClick={()=>setScene(i)} className={scene===i?'active':''}>{label}</button>)}</div><div className="scene-demo"><div className="scene-list">{scenes.map(([label,title],i)=><button key={label} onClick={()=>setScene(i)} className={scene===i?'active':''}><small>0{i+1}</small>{title}</button>)}</div><div className="scene-screen"><img src={`/assets/${scenes[scene][2]}`} alt="ShimoDocs workflow preview"/><div className="scene-caption"><Eyebrow>Live workflow preview</Eyebrow><h3>{scenes[scene][1]}</h3><p>Shared context, visible handoffs and a clear next step for the team.</p></div></div></div></section>
  <section className="section home-blog"><div><Eyebrow>From the ShimoDocs journal</Eyebrow><h2>Ideas for doing<br/><span className="gradient">better work.</span></h2></div><Link className="text-link" to="/blog">Read the journal ↗</Link></section>
 </div>}
