#!/usr/bin/env node
// Emits the client-side content metadata modules.
//
// Runs as the `prebuild` and `predev` step so the listings always match the
// Markdown on disk. Only metadata lands in src/generated; article and guide
// bodies are rendered into static HTML by the prerenderer and never enter the
// bundle.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ARTICLE_DOCS } from './article-docs.mjs'
import { CATEGORIES, loadPosts, toClientRecord } from './blog-content.mjs'
import { buildNav, loadDocs, sortDocs, toDocClientRecord } from './docs-content.mjs'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(rootDir, 'src', 'generated')
const outFile = join(outDir, 'blog-posts.js')

const posts = loadPosts()
const records = posts.map(toClientRecord)

const counts = new Map()
for (const post of posts) counts.set(post.category, (counts.get(post.category) || 0) + 1)

const categories = CATEGORIES.map(category => ({
  ...category,
  count: counts.get(category.id) || 0,
})).filter(category => category.count > 0)

const banner = `// Generated by scripts/build-content.mjs — do not edit by hand.
// Source of truth: content/blog/*.md
`

// The archive prints "Updated <date>". Deriving it from the newest publication
// date alone made the page claim it was last touched in August while a dozen
// articles in it had been revised in September — the page understating its own
// freshness is the one direction a reader cannot detect and a crawler believes.
const lastUpdated = records
  .map(record => record.updated || record.date)
  .filter(Boolean)
  .sort()
  .pop()

const body = `${banner}
export const BLOG_POSTS = ${JSON.stringify(records, null, 2)}

export const BLOG_CATEGORIES = ${JSON.stringify(categories, null, 2)}

export const BLOG_UPDATED = ${JSON.stringify(lastUpdated || null)}
`

mkdirSync(outDir, { recursive: true })
writeFileSync(outFile, body)

const totalWords = posts.reduce((sum, post) => sum + post.words, 0)
console.log(
  `Blog content: ${posts.length} posts, ${totalWords.toLocaleString('en-US')} words, ` +
    `${categories.length} categories -> src/generated/blog-posts.js`,
)
for (const category of categories) {
  console.log(`  ${category.label.padEnd(22)} ${String(category.count).padStart(3)}`)
}

// ------------------------------------------------------------ documentation

const docs = loadDocs()
const ordered = sortDocs(docs)
const nav = buildNav(docs)

const docsBody = `${banner}
export const DOCS = ${JSON.stringify(ordered.map(toDocClientRecord), null, 2)}

export const DOC_NAV = ${JSON.stringify(
  nav.map(group => ({
    id: group.id,
    label: group.label,
    docs: group.docs.map(doc => toDocClientRecord(doc)),
    subgroups: group.subgroups.map(subgroup => ({
      id: subgroup.id,
      label: subgroup.label,
      docs: subgroup.docs.map(doc => toDocClientRecord(doc)),
    })),
  })),
  null,
  2,
)}
`

writeFileSync(join(outDir, 'docs-nav.js'), docsBody)

const docWords = docs.reduce((sum, doc) => sum + doc.words, 0)
console.log(
  `Documentation: ${docs.length} guides, ${docWords.toLocaleString('en-US')} words, ` +
    `${nav.length} sections -> src/generated/docs-nav.js`,
)
for (const group of nav) {
  console.log(`  ${(group.label || 'Overview').padEnd(34)} ${String(group.docs.length).padStart(3)}`)
}

// ------------------------------------------------- category documentation

// Each topic page lists the guides its own articles point at.
//
// Derived from ARTICLE_DOCS rather than written again here: the editorial link
// map already says which guide proves which article, so counting those links per
// category gives the guides a topic page should lead with. A guide that no
// article in the category cites is not listed, which keeps the block honest
// instead of turning every topic page into the same list of five guides.
const docsById = new Map(docs.map(doc => [doc.id, doc]))
const categoryCounts = new Map()
for (const post of posts) {
  for (const id of ARTICLE_DOCS[post.slug] || []) {
    if (!docsById.has(id)) continue
    const counts = categoryCounts.get(post.category) || new Map()
    counts.set(id, (counts.get(id) || 0) + 1)
    categoryCounts.set(post.category, counts)
  }
}

const categoryDocs = {}
for (const [category, counts] of categoryCounts) {
  categoryDocs[category] = [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 4)
    .map(([id]) => {
      const doc = docsById.get(id)
      return { url: doc.url, title: doc.title, description: doc.description }
    })
}

const categoryBody = `${banner}
export const CATEGORY_DOCS = ${JSON.stringify(categoryDocs, null, 2)}
`
writeFileSync(join(outDir, 'blog-category-docs.js'), categoryBody)

console.log(
  `Category guides: ${Object.keys(categoryDocs).length} topics, ` +
    `${Object.values(categoryDocs).reduce((sum, entries) => sum + entries.length, 0)} guide links ` +
    '-> src/generated/blog-category-docs.js',
)
