#!/usr/bin/env node
// Emits the client-side blog metadata module.
//
// Runs as the `prebuild` and `predev` step so the listing always matches the
// Markdown on disk. Only metadata lands in src/generated; article bodies are
// rendered into static HTML by the prerenderer and never enter the bundle.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { CATEGORIES, loadPosts, toClientRecord } from './blog-content.mjs'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(rootDir, 'src', 'generated')
const outFile = join(outDir, 'blog-posts.js')

const posts = loadPosts()
const records = posts.map(toClientRecord)

const counts = new Map()
for (const post of posts) counts.set(post.category, (counts.get(post.category) || 0) + 1)

const categories = CATEGORIES.map(category => ({
  ...category,
  count: counts.get(category.id) || 0,
})).filter(category => category.count > 0)

const banner = `// Generated by scripts/build-content.mjs — do not edit by hand.
// Source of truth: content/blog/*.md
`

const body = `${banner}
export const BLOG_POSTS = ${JSON.stringify(records, null, 2)}

export const BLOG_CATEGORIES = ${JSON.stringify(categories, null, 2)}

export const BLOG_UPDATED = ${JSON.stringify(records[0]?.date || null)}
`

mkdirSync(outDir, { recursive: true })
writeFileSync(outFile, body)

const totalWords = posts.reduce((sum, post) => sum + post.words, 0)
console.log(
  `Blog content: ${posts.length} posts, ${totalWords.toLocaleString('en-US')} words, ` +
    `${categories.length} categories -> src/generated/blog-posts.js`,
)
for (const category of categories) {
  console.log(`  ${category.label.padEnd(22)} ${String(category.count).padStart(3)}`)
}
