#!/usr/bin/env node
// Emits the client-side content metadata modules.
//
// Runs as the `prebuild` and `predev` step so the listings always match the
// Markdown on disk. Only metadata lands in src/generated; article and guide
// bodies are rendered into static HTML by the prerenderer and never enter the
// bundle.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { CATEGORIES, loadPosts, toClientRecord } from './blog-content.mjs'
import { buildNav, loadDocs, sortDocs, toDocClientRecord } from './docs-content.mjs'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(rootDir, 'src', 'generated')
const outFile = join(outDir, 'blog-posts.js')

const posts = loadPosts()
const records = posts.map(toClientRecord)

const counts = new Map()
for (const post of posts) counts.set(post.category, (counts.get(post.category) || 0) + 1)

const categories = CATEGORIES.map(category => ({
  ...category,
  count: counts.get(category.id) || 0,
})).filter(category => category.count > 0)

const banner = `// Generated by scripts/build-content.mjs — do not edit by hand.
// Source of truth: content/blog/*.md
`

const body = `${banner}
export const BLOG_POSTS = ${JSON.stringify(records, null, 2)}

export const BLOG_CATEGORIES = ${JSON.stringify(categories, null, 2)}

export const BLOG_UPDATED = ${JSON.stringify(records[0]?.date || null)}
`

mkdirSync(outDir, { recursive: true })
writeFileSync(outFile, body)

const totalWords = posts.reduce((sum, post) => sum + post.words, 0)
console.log(
  `Blog content: ${posts.length} posts, ${totalWords.toLocaleString('en-US')} words, ` +
    `${categories.length} categories -> src/generated/blog-posts.js`,
)
for (const category of categories) {
  console.log(`  ${category.label.padEnd(22)} ${String(category.count).padStart(3)}`)
}

// ------------------------------------------------------------ documentation

const docs = loadDocs()
const ordered = sortDocs(docs)
const nav = buildNav(docs)

const docsBody = `${banner}
export const DOCS = ${JSON.stringify(ordered.map(toDocClientRecord), null, 2)}

export const DOC_NAV = ${JSON.stringify(
  nav.map(group => ({
    id: group.id,
    label: group.label,
    docs: group.docs.map(doc => toDocClientRecord(doc)),
    subgroups: group.subgroups.map(subgroup => ({
      id: subgroup.id,
      label: subgroup.label,
      docs: subgroup.docs.map(doc => toDocClientRecord(doc)),
    })),
  })),
  null,
  2,
)}
`

writeFileSync(join(outDir, 'docs-nav.js'), docsBody)

const docWords = docs.reduce((sum, doc) => sum + doc.words, 0)
console.log(
  `Documentation: ${docs.length} guides, ${docWords.toLocaleString('en-US')} words, ` +
    `${nav.length} sections -> src/generated/docs-nav.js`,
)
for (const group of nav) {
  console.log(`  ${(group.label || 'Overview').padEnd(34)} ${String(group.docs.length).padStart(3)}`)
}
